### ISSUE TITLE
Store public key for easier access

### ISSUE THREAD

**Issue by bryopsida** [bryopsida/k8s-wireguard-mgr#70]
What
---
As a maintainer of a wireguard vpn, I want easy access to the public key. Currently, when this is used in bryopsida/wireguard-chart, it generates the private key on first install but a maintainer must extract the public key from logs which can be difficult to automate. In cases where maintainers are using this to automate the key generation, we should provide a way for maintainers to store the public key in the kubernetes api.  The public key should be stored in a separate resource than the private key so RBAC can be used to provide access to the public key without also having to provide access to the private key. Maintainers should be able to specify the name and resource type (secret or configmap), but these should be optional, if not provided it should default to a secret and suffixing the name provided for the private key secre for the name.

Relates to: https://github.com/bryopsida/wireguard-chart/issues/74

**Comment by martivo** [comment]
I have tested the PR code with the following helm values:
```
            extraSideCars:
                - image: nginxinc/nginx-unprivileged
                  name: pubkey
                  volumeMounts:
                    - mountPath: /usr/share/nginx/html/index.html
                      name: pubkey
                      subPath: publickey
            keygenJob:
                wireguardMgrImage:
                    repository: entigolabs/k8s-wireguard-mgr
                    tag: latest
            metrics:
                enabled: false
                serviceMonitor:
                    enabled: false
            service:
                annotations:
                    external-dns.alpha.kubernetes.io/hostname: REDACTED_HOSTNAME
                    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "REDACTED_ARN_OF_CERTMANAGER"
                    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
                extraPorts:
                    - name: pubkey
                      port: 443
                      protocol: TCP
                      targetPort: 8080
            volumes:
                - name: pubkey
                  secret:
                    secretName: wireguard-wg-generated-public
            wireguard:
                clients: []
                serverAddress: 172.31.200.1/24
                serverCidr: 172.31.200.0/24

```

I was able to do `curl https://REDACTED_HOSTNAME` and retrieve the public key of the server.
